### ISSUE TITLE
Issues with jupyter cells and larger LaTeX equations

### ISSUE THREAD

**Issue by Sayam753** [danielfrg/mkdocs-jupyter#11]
Hi @danielfrg 

Thanks for this fantastic library. I am loving it. Here are a few issues I have encountered while using `mkdocs-jupyter`. I am very less familiar with CSS/JS so I used hacks to solve these issues.

1. Responsiveness breaks on smaller screens for larger lines in jupyter cells.
![Screenshot 2020-05-31 at 8 51 50 PM](https://user-images.githubusercontent.com/43073325/83356003-b1105380-a380-11ea-89d1-31a2f1854ef9.png)

To solve this, I have created a css file with code below and linked that in `mkdocs.yml`.
```css
pre {
    overflow: auto;
}
```
I want to ask if this `responsiveness behaviour` is expected or  is it more likely an issue?

2. Similarly, rendering of larger LaTex equations breaks on smaller screens

![WhatsApp Image 2020-05-31 at 9 10 04 PM](https://user-images.githubusercontent.com/43073325/83356383-74922700-a383-11ea-856a-ff3b12fe4238.jpeg)

Sorry for ugly screenshots.
I have solved this issue, by updating `mathjaxscript.src` in `templates.py` module to this - 
```js
mathjaxscript.src = "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML";
```
Again, I want to ask if this `LaTeX behaviour` is expected or  is it more likely an issue?

Checkout this [web page](https://www.codingpaths.com/testing/gsoc/variational-inference/) which I have deployed to inspect the issues live.

**Comment by danielfrg** [comment]
Thanks for the detailed report and passing allowing those fixes!

I have updated the version of MathJax and that should fix those rendering issues.

For the CSS code for the pre blocks I noticed it only happens with the material theme.
See this screenshot that uses the default theme the default theme without your fix:

<img width="497" alt="Screen Shot 2020-05-31 at 16 50 41" src="https://user-images.githubusercontent.com/1580714/83363449-2539ff80-a35f-11ea-8544-58b06edcbfa1.png">

So I would recommend to keep that small CSS on your site CSS instead of including it here, I will include that fix on my own websites.

I would say that in general with different themes that use diff frontend libraries these type issues and small fixes are everywhere for Jupyter Notebooks generated content, its kinda how it is. I include some that I have learned over the years but this things are always changing.

Thanks again for the report. I will close this issue but feel free to ask any other questions!
