### ISSUE TITLE
Embed pictures and downloadable notebook

### ISSUE THREAD

**Issue by drewlr** [danielfrg/mkdocs-jupyter#2]
Hi there, first of all thanks for putting this repo together! We are trying to use it to embed Jupyter notebooks tutorials directly into a docs site.

More than an issue this is a shameless request for features / advice :)

It would be great to:

- have ability to download the notebook directly from the top of the rendered page, similar to what's done here - https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py

- have ability to render images that are embed within original markdown cells

Would you have any advice on how to go about it?

**Comment by ofek** [comment]
@drewlr Does this plugin work with https://github.com/squidfunk/mkdocs-material/issues/1522 ?

**Comment by ofek** [comment]
@drewlr Does this plugin work with https://github.com/squidfunk/mkdocs-material ?

**Comment by drewlr** [comment]
@ofek it worked with mkdocs-material - although for now we ended up using https://github.com/jupyter/nbconvert to quickly address embed images in md cells

**Comment by ofek** [comment]
@drewlr Good to hear, thanks! I wonder if this would work for you https://github.com/greenape/mknotebooks

**Comment by drewlr** [comment]
@ofek Thanks for the pointer. If I recall correctly, I tried that one as well, and there were some issues with the formatting - hence the jupyter nbconvert + some custom python for a light touch of formatting.

**Comment by danielfrg** [comment]
Thanks for the suggestions and reports.

About the embedded images, they should be rendered as part of the Notebook, for example matplotlib plots do work for me, look at the tests notebooks and see if you can reproduce https://github.com/danielfrg/mkdocs-jupyter/tree/master/mkdocs_jupyter/tests/mkdocs

If you want and have time try any newer version but at least on master this should be working.
If you have images in MD chunks, those will only work in the mkdocs site if the URL are valid form there mkdocs site, not the notebook.

I also added the ability to include the source notebook file as part of the site, this gives you the ability to include a download button as part of the theme.
I think this a better approach than actually adding a link as part of the notebook render since you can customize it how ever you need!

See docs for that here: https://github.com/danielfrg/mkdocs-jupyter#download-notebook-link

I am gonna close as the feature is there and I dont think there is a render issue anymore, feel free to open a new issue if you see it again.
