### ISSUE TITLE
support HTML outputs that use RequireJS

### ISSUE THREAD

**Issue by afeld** [danielfrg/mkdocs-jupyter#21]
I'm using [Plotly Express](https://plotly.com/python/plotly-express/) to generate charts within my notebooks, and am getting `Uncaught ReferenceError: require is not defined`. The issue seems to be that Plotly is outputting HTML with an embedded `<script>`, which expects RequireJS to be present. I tried making a [custom theme](https://www.mkdocs.org/user-guide/custom-themes/) that inherits from `mkdocs` to inject RequireJS, but no matter which block I tried, it caused even _more_ JS errors.

## Steps to reproduce

1. Set up a site with mkdocs-jupyter
1. Copy in [this example notebook](https://gist.githubusercontent.com/afeld/9eef902fdd9f6e14eb4ab3cc75a98267/raw/d1eecb61a812352a76a308ec77cc4f0116b404f5/example.ipynb), which contains [this Plotly example](https://plotly.com/python/plotly-express/#scatter-line-area-and-bar-charts)
1. Add to the `nav`

**Comment by danielfrg** [comment]
I do this for mkdocs-material:  https://github.com/danielfrg/jupyter-flex/blob/master/docs/theme/partials/nav.html#L8-L11

I will close as its not related to the plugin but I agree its very annoying, specially since require break the search box in mkdocs-material. Hopefully this becomes better with future versions of plotly.
