### ISSUE TITLE
Error reading page 'Untitled.ipynb': basic.tpl

### ISSUE THREAD

**Issue by arjunskumar** [danielfrg/mkdocs-jupyter#25]
When include notebook to the mkdocs.yml , I'm getting this error. I have installed the plugins correctly. 

Python version : 3.6.9

**Comment by PaulCCCCCCH** [comment]
Same issue here.
`pip install --upgrade nbconvert==5.5` 
Works for me.

**Comment by arjunskumar** [comment]
Thanks @PaulCCCCCCH

**Comment by AbdealiJK** [comment]
Just documenting here with more details as I got the same issue.

The last version of mkdocs-jupyter which supports python 3.6 is mkdocs-jupyter==0.13.0 (June 2020)
Since then, nbconvert has moved to 6.x (Sep 2020)

So, to use mkdocs_jupyter on python 3.6 - you need to force pip to install an older version of nbconvert.

Ideally to support python 3.6 users - it would be awesome if a backward compatibility patch of mkdocs-jupyter 1.13.1 could be created which patches the requirement on nbconvert to `nbconvert<5`.

So, currently the solutoins are:
 - Either upgrade to python 3.7
 - Or, use nbconvert 5.x
